services:
  db:
    container_name: postgres-db-skeleton
    image: postgres
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      PGDATA: /data/postgres
      POSTGRES_DB: db_name
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  db:
    driver: bridge

volumes:
  db:
